export const VaccineActionTypes= {
    LOADING_SPINNER:"LOADING_SPINNER",
    GET_STATES:"GET_STATES",
    GET_DISTRICT:"GET_DISTRICT",
    FETCH_SLOTS_BY_DIST:"FETCH_SLOTS_BY_DIST",
    FETCH_SLOTS_BY_PIN:"FETCH_SLOTS_BY_PIN",
    GET_DASHOBORD_DATA:"GET_DASHOBORD_DATA",
    GET_VACCIN_SLOTS:"GET_VACCIN_SLOTS"
} 